### ISSUE TITLE
FP 16 Pretrained MODEL 

### ISSUE THREAD

**Issue by Choi-YeongJoon** [hisfog/SfMNeXt-Impl#27]
I am very interested in your work! I ran your model in TensorRT, C++. The fps is so low that I think I need to run a model with fp16 precision. Do you have a pretrained model trained with fp16 precision? Can I possibly get it?

**Comment by hisfog** [comment]
The ConvNeXt model is not effcient (392.2 GMACs), you can try the `KITTI (Efficient-b5)` model (70.35 GMACs), which is much more faster and also accurate enough.
For fp16 models, they should be trained from scratch in fp16 precision, I didn't do that training, since this repo is not for industrial use cases.
